# -*- coding: utf-8 -*-
"""практика 7.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGlDeYDe_6f0TjZt_TdWehnL77RgtcsF
"""

def check_input(element):
    return isinstance(element, str)

def get_substring(s):
    n = len(s)
    longest_substr = ""
    start = 0
    char_index_map = {}

    for end in range(n):
        if s[end] in char_index_map:
            start = max(start, char_index_map[s[end]] + 1)
        char_index_map[s[end]] = end
        if end - start + 1 > len(longest_substr):
            longest_substr = s[start:end + 1]

    return longest_substr

def main(input_list):

    longest_string_index = -1
    longest_string_length = 0
    longest_string = ""

    for index, element in enumerate(input_list):
        if check_input(element):
            if len(element) > longest_string_length:
                longest_string_length = len(element)
                longest_string_index = index
                longest_string = element

    if longest_string_index == -1:
        return -1, ""

    longest_substring = get_substring(longest_string)
    return longest_string_index, longest_substring

input_data = [[0, 4, 8], 'abca', 7, 'aaaaa']
result = main(input_data)
print(result)